### ISSUE TITLE
Recently published modules that I was beta tester for still show as "In Beta" even when not

### ISSUE THREAD

**Issue by TheAndyMac** [cherryaudio/store-issues#91]
Browser Report:  https://www.whatsmybrowser.org/b/LZXEF

### Description:
I was helping Carly (Poohbear https://store.cherryaudio.com/manufacturers/poohbear) beta testing her new suite of modules. 

Many of them have been recently published as the bundle https://store.cherryaudio.com/bundles/poohbears-goodie-bag, and I have purchased them - the issue is that many of the published are still showing in my “In Beta” section. 

I have checked with Carly, and some are to be expected as still in beta - specifically Store and Forward, Speed Tested, Spacer, Lo Port, Hi Port and High Low Monitor - but the rest are fully published, not showing as Beta in her dashboard and should not be listing as "In Beta" in VM (but I'm assuming this is a store-side issue).

As you can see from the screenshot, First Counter, Flip Flop Counter, Flip Flop Switcher, GaToR, Min Max, Transer and Trigate are all still showing in my “In Beta” section:

![Screenshot](https://user-images.githubusercontent.com/12783814/128981053-f0c24467-1dec-423c-8b96-3e0f174e65c7.png)

### Detailed steps to reproduce the issue:
1. Poohbear was developing and testing modules. Added me as beta tester. They all became available for me to test, as expected.
2. Poohbear then published many of them (list in description) as a bundle https://store.cherryaudio.com/bundles/poohbears-goodie-bag and I purchased the bundle.
3. Some modules got correctly downloaded into my VM as "New/Updated" but some remained showing "In Beta" even though they were no longer in beta.
4. Poohbear checked her side for published items and they all offered "Put Into Beta" option, implying that they had correctly been removed from beta status.
5. I clear the modules/cache, resync'd VM and reloaded all of the modules, but the problem still remains.

**Comment by TheAndyMac** [comment]
Hi Andy, any further updates on this? I'm still seeing the same issue. It may be worth noting that I am also down as a beta tester for Black Cloud Industries (BCI) https://store.cherryaudio.com/manufacturers/black-cloud-industriesand have 45 modules showing in beta for them with the one published (K-String) listed correctly in Oscillators and correctly NOT showing up in the "In Beta".

**Comment by techenby** [comment]
Yeah I'm still looking into this, sorry it's taking forever! There's a lot going on with the API with a lot of overrides for this and that so it's a little complicated and could do with some simplifying. Good thing we're working on API performance!

**Comment by TheAndyMac** [comment]
No problem - I'm working through another, maybe related issue in that some of the modules I am testing are showing older versions than he has currently published... I've asked the developer to remove me as beta tester to see if that "unscrambles" things and then re-add me. I'll feed this back to you once we've done it, in case it sheds some light on the issue.

Regards
Andrew Macaulay

**Comment by TheAndyMac** [comment]
ESCALATE THIS ISSUE PLEASE - NEEDS TO BE HIGH PRIORITY

This is a bigger issue that I thought! The beta versions that I can see on my account are locked into old versions, so I can't actually test later beta builds of a developer's modules!

I have just run some tests with PoohBear and when I am removed from his beta testing, none of his modules (only a few of which are currently in beta) show in the beta tab in Voltage Modular --- and the correct version of the module Flip Flop Switcher gets installed (build 14, his latest published build) but if I then am added back as a beta tester, ALL his modules that have, at some point, been in beta (i.e. not just those currently in beta) are shown in the beta tab AND the Flip Flop Switcher (the only one I am currently testing here) REVERTS back to BUILD 8 - probably the last build before he first published it.

This makes the Beta Tester role pretty much useless, when it occurs... it feels like there is some history information that is stored about the beta modules which is not being updated correctly. Is there a way to force delete this history for a user?

Regards
Andrew Macaulay

From: Andrew Macaulay
Sent: Monday, October 18, 2021 9:05 PM
To: cherryaudio/store-issues ***@***.***>
Subject: RE: [cherryaudio/store-issues] Recently published modules that I was beta tester for still show as "In Beta" even when not (#91)

No problem - I'm working through another, maybe related issue in that some of the modules I am testing are showing older versions than he has currently published... I've asked the developer to remove me as beta tester to see if that "unscrambles" things and then re-add me. I'll feed this back to you once we've done it, in case it sheds some light on the issue.

Regards
Andrew Macaulay

**Comment by techenby** [comment]
Yeah looking through the database, there’s a ton of modules that have multiple builds in beta. I didn’t design it to have multiples in beta, but apparently didn’t code a force update to previous builds when a new one is in beta.

I’m currently fixing the data in the database, but will also add a code fix to prevent multiple builds being in beta at once.

Andy

**Comment by TheAndyMac** [comment]
Thank you – let me know when I should test it again 😊

Regards
Andrew Macaulay

**Comment by TheAndyMac** [comment]
Hi Andy, any updates on the fixes yet?

Regards
Andrew Macaulay

From: Andrew Macaulay
Sent: Tuesday, October 19, 2021 4:36 PM
To: cherryaudio/store-issues ***@***.***>
Subject: RE: [cherryaudio/store-issues] Recently published modules that I was beta tester for still show as "In Beta" even when not (#91)

Thank you – let me know when I should test it again 😊

Regards
Andrew Macaulay

**Comment by techenby** [comment]
I did the database clear of duplicate beta builds but the fix should be in a release today or Monday.

**Comment by TheAndyMac** [comment]
Thanks, I’ll have a look after Monday to see if it’s all working as expected for me.
Regards
Andrew Macaulay

**Comment by TheAndyMac** [comment]
Hi Andy, should I need to do anything to get the correct beta list and versions (like come out of the beta and get joined again) or should it automatically update my account with the correct betas from others?

I’m not seeing any change currently on the list of beta modules, including the issue with an old version (build 8) being listed when the published version is later and there is a subsequent beta as well.

Regards
Andrew Macaulay

From: Andrew Macaulay
Sent: Thursday, October 21, 2021 5:30 PM
To: cherryaudio/store-issues ***@***.***>
Subject: RE: [cherryaudio/store-issues] Recently published modules that I was beta tester for still show as "In Beta" even when not (#91)

Thanks, I’ll have a look after Monday to see if it’s all working as expected for me.
Regards
Andrew Macaulay

**Comment by techenby** [comment]
Fixed in 3.7.0 -> not closing cause I'm sure you want to test :)

**Comment by TheAndyMac** [comment]
Thanks Andy, I’ll get myself added back into a beta program and test this – and let you know if all good 😊

Regards
Andrew Macaulay

**Comment by TheAndyMac** [comment]
Andy, sorry but this is still not working for me ☹

Before I got added back into Poohbear’s (Carly’s) beta, I had 45 betas listed (all of which are from Black Cloud Industries). After accepting the beta invite I now have 62 listed as beta, when I believe Carly has published all but one of them - so should only have 46 showing. To be 100% sure, I have deleted the modules and cleared the cache and allowed it to get the catalogue again, but still the same.

Also, the Flip Flop Switcher module that was showing an earlier build than the published version (the one I knew about) has reverted back to the old version, showing build 8 rather than the current build which is (I think) 15.

Removed myself from his beta again so that have the latest builds.

Regards
Andrew Macaulay

From: Andrew Macaulay
Sent: Tuesday, November 16, 2021 7:50 AM
To: cherryaudio/store-issues ***@***.***>
Subject: RE: [cherryaudio/store-issues] Recently published modules that I was beta tester for still show as "In Beta" even when not (#91)

Thanks Andy, I’ll get myself added back into a beta program and test this – and let you know if all good 😊

Regards
Andrew Macaulay
