### ISSUE TITLE
Search dialog brings up phantom manufacturers

### ISSUE THREAD

**Issue by SynthDan** [cherryaudio/store-issues#97]
Right now, all the VM900 modules are hidden in the store.

Go to the store page and search for "VM900" or just click here: https://store.cherryaudio.com/search?q=VM900

As you'll see in the attached photo, even though "No results" are displayed, "Cherry Audio / MRB" are still mistakenly listed in the Manufacturers pane. This isn't just a bug, it's dangerous - it can give clever users a clue into what we're releasing next. For example, doing a search for "Mercury" shows "Cherry Audio" under the Manufacturers column as well. Mercury-4 is hidden in the store.

![Search Phantom Manufacturer](https://user-images.githubusercontent.com/13699795/131383703-299faacc-5bd3-4f7f-9cbc-37effe7d4fb1.jpg)

**Comment by scottmetoyer** [comment]
Fixed in 3.8.10

**Comment by SynthDan** [comment]
Hi Scott, is this issue actually fixed? This link https://store.cherryaudio.com/search?q=VM900 still shows "No results" and "Cherry Audio / MRB", unchecked, in the Manufacturers list. If I check "Cherry Audio / MRB" all the VM900 modules show up. But then refreshing the page again shows "No results" and "Cherry Audio / MRB" unchecked. How odd!

**Comment by SynthDan** [comment]
Actually, If I log out and go to that link, it works perfectly. When I log back in, "Cherry Audio / MRB" is unchecked every time.

**Comment by scottmetoyer** [comment]
Got it - clearly I missed something! I'll take a look and report back with a fix.

**Comment by scottmetoyer** [comment]
Ok - looks like there are some nuances with logged in users who have removed this manufacturer or hidden owned products. I'll have a fix wrapped up today.

**Comment by scottmetoyer** [comment]
Hi Dan - a revised fix for this went out in 3.8.11. Can you check that it's behaving as expected now?

**Comment by SynthDan** [comment]
Scott, there's no change for me. I logged out of dan@cherryaudio.com and logged in to my test account, danrg@aol.com, and everything works fine. So I guess the problem is related to my company account.

That same search always comes up with Cherry Audio / MRB unchecked. I don't have 'Hide Products I Own' checked. It just, for whatever reason, insists that I don't want to view Cherry Audio / MRB as a manufacturer.

Since this doesn't affect normal customers, it's not a big deal, but it's curious.

**Comment by scottmetoyer** [comment]
Hi - that’s frustrating. I’ll do some additional research looking at your
account specifically to see if there are any anomalies there.
